name: tests
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup uv (and Python)
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install project (dev)
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        run: uv run pytest -q tests
